# Form implementation generated from reading ui file 'ui_imagedialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(694, 636)
        self.readWashingtonBtn = QtWidgets.QPushButton(parent=Dialog)
        self.readWashingtonBtn.setGeometry(QtCore.QRect(510, 20, 151, 51))
        self.readWashingtonBtn.setObjectName("readWashingtonBtn")
        self.readDigitalBtn = QtWidgets.QPushButton(parent=Dialog)
        self.readDigitalBtn.setGeometry(QtCore.QRect(510, 90, 151, 51))
        self.readDigitalBtn.setObjectName("readDigitalBtn")
        self.readTechBtn = QtWidgets.QPushButton(parent=Dialog)
        self.readTechBtn.setGeometry(QtCore.QRect(510, 160, 151, 51))
        self.readTechBtn.setObjectName("readTechBtn")
        self.listView = QtWidgets.QListView(parent=Dialog)
        self.listView.setGeometry(QtCore.QRect(30, 20, 461, 581))
        self.listView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.listView.setBatchSize(1000)
        self.listView.setObjectName("listView")
        self.readReadWriteBtn = QtWidgets.QPushButton(parent=Dialog)
        self.readReadWriteBtn.setGeometry(QtCore.QRect(510, 230, 151, 51))
        self.readReadWriteBtn.setObjectName("readReadWriteBtn")
        self.exitBtn = QtWidgets.QPushButton(parent=Dialog)
        self.exitBtn.setGeometry(QtCore.QRect(510, 550, 151, 51))
        self.exitBtn.setObjectName("exitBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.readWashingtonBtn.setText(_translate("Dialog", "Читать WashingtonPost"))
        self.readDigitalBtn.setText(_translate("Dialog", "Читать digitaltrends"))
        self.readTechBtn.setText(_translate("Dialog", "Читать techspot"))
        self.readReadWriteBtn.setText(_translate("Dialog", "Читать readwrite"))
        self.exitBtn.setText(_translate("Dialog", "Выход"))
